name: Build and deploy Node.js app to Azure Web App - DigitalDashborad

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version for client
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Set up Node.js version for server
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build server
        working-directory: ./server
        run: |
          npm install
          # Add other build steps for the server if needed

      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          name: client-build
          path: ./client/build

      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-build
          path: ./server/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download client artifact
        uses: actions/download-artifact@v2
        with:
          name: client-build

      - name: Download server artifact
        uses: actions/download-artifact@v2
        with:
          name: server-build

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "DigitalDashborad"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A49EDDE42058452196D11CAE0AC2ED38 }}
          package: .

